spring:
  datasource:
    url: jdbc:mysql://localhost:3307/spring_6_rest_mvc?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: spring_admin
    password: password
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
#  flyway:
#    enabled: true
#    user: spring_admin
#    password: password
